log = interactiveSerial.log

container_image = osdf:///ospool/uc-shared/public/OSG-Staff/xalim_stat/R_tidyverse_FITSio.sif

transfer_input_files = by_region/over_300k/Indonesia.csv, by_region/over_300k/Ireland.csv, ranking_songs.R, runScript_interactive.sh, submit_ranking_songs.sub

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_memory = 1GB
request_disk = 1GB

queue