log = log/ranking_song/$(Cluster)_$(i)_agg.log
error = error/ranking_songs/$(Cluster)_$(i)_agg.err

container_image = osdf:///ospool/uc-shared/public/OSG-Staff/xalim_stat/R_tidyverse_FITSio.sif

executable = ./runScriptNoArg.sh
arguments = ranking_songs_agg.R

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ranking_songs.tar

request_cpus = 1
request_memory = 2GB
request_disk = 5GB

