log = log/ranking_song/test_$(Cluster)_$(i)_AGG.log
error = error/ranking_songs/test_$(Cluster)_$(i)_AGG.err

container_image = R_tidyverse_FITSio_patchwork_maps.sif

executable = ./runScriptNoArg.sh
arguments = ranking_songs.tar ranking_songs_agg.R

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ranking_songs.tar, runScriptNoArg.sh, ranking_songs_agg.R

request_cpus = 1
request_memory = 2GB
request_disk = 5GB

queue